insert into exchange_value(id,currency_from,currency_to,conversion_multiple,port) values(10001,'USD','INR',65,0)
insert into exchange_value(id,currency_from,currency_to,conversion_multiple,port) values(10002,'EUR','INR',35,0)
insert into exchange_value(id,currency_from,currency_to,conversion_multiple,port) values(10003,'AUD','INR',55,0)
insert into exchange_value(id,currency_from,currency_to,conversion_multiple,port) values(10004,'DNR','INR',85,0)
insert into exchange_value(id,currency_from,currency_to,conversion_multiple,port) values(10005,'RUB','INR',15,0)
insert into exchange_value(id,currency_from,currency_to,conversion_multiple,port) values(10006,'YEN','INR',45,0)